### ISSUE TITLE
Compile instructions?

### ISSUE THREAD

**Issue by Plawasan** [rbaron/eink-ha#2]
Hi, thanks for making this public - would you mind providing at least some basics for how to compile and upload this? I have everything set up HW wise, I can upload sketches from the Arduino IDE to the ePaper, I know how to upload ESPHome config etc but I'm a bit lost when it comes to gcc and compiling and uploading .cpp.. I'm on Ubuntu. Thanks!

**Comment by rbaron** [comment]
Hey @Plawasan,

This is a [PatformIO](https://platformio.org/) project. Once you [install it](https://platformio.org/install/cli), you should be able to just type `platformio run` and `platformio run -t upload` (see [example](https://docs.platformio.org/en/stable//core/userguide/demo.html#blink-project)).

Alternatively, and that's why I personally use, you can install the [PlatormIO VSCode extension](https://platformio.org/install/ide?install=vscode). With this, you can just click the build button in the UI and it will compile and upload the code to your board for you.

Please let me know if this helps.

**Comment by Plawasan** [comment]
Thanks, helped a lot! I was able to get update the credentials, connect to wifi/HA and update the display but I'm having a tough time updating it to display my own entities.. I updated lib/eink/eink/ha_client.cpp with my CO2 sensor, external temp, openweather entity, I've cleaned the build cache, recompiled, uploaded.. no dice. 

Anyway, I appreciate the help, I realize this is not meant to be a finished product so I'm really not expecting it to all work seamlessly..

**Comment by rbaron** [comment]
Happy to hear you're making progress. What's the issue you're seeing? You mentioned you were able to update the display, but not with your own data? I think the first step is to identify where the issue is - is in the API call? Do you see your data in the response?

**Comment by Plawasan** [comment]
I know I'm connecting to HA, one of my helpers happens to match the name you're filtering for and does show up on the display:

```
Before wifi 1
Connected to WiFi: 192.168.1.167!
After wifi 2319
HTTP status code: 200
JSON: 244
Soil Moisture Threshold: 40.000000 (error: ), last updated: Saturday Nov 06 10:28
```

but even if I simply update the names of the entities in ha_client.cpp to match mine then I don't see anything reporting for the temperatures or co2 (I happen to also use mhz-19...). Here's another nooby question - I know how to monitor the serial output but where do I actually see the output of LOG()?

**Comment by rbaron** [comment]
It seems like the issue is in the filtering and/or data parsing. I would start by doing a manual call (using `cURL` or something similar) to the home assistant API.

This is the call I used during development:

```bash
$ curl -H "Authorization: Bearer <your token>" http://your-home-assistant-addr/api/states | less
```

(You can also pipe it through `jq` if you have it installed for nicer formatting: `[...] /api/states | jq . | less`).

This will give you a list of all your entities and their IDs. You can use it to double check your filtering rules and your parsing functions.

**Comment by Plawasan** [comment]
That works perfectly fine... jq . | wc -l gives me 27k lines so definitely enough data to play with, I can see that the specific entities that I was trying to display are in fact listed.

I'm decent with python when it comes to parsing data structures but cpp is not my cup of tea. I see that you have logging set up in quite a few places but as I mentioned above, I'm not sure how do I get to the output of LOG(), doesn't see to be dumped to /dev/ttyUSB0..

**Comment by Plawasan** [comment]
I spent a bit more time trying to get things to work, still no luck.. I did figure out that LOG() actually prints out to serial console, the issue is that the functions where I added it simply never got called.. 

I tried to simplify things a bit by getting status for a single entity instead of getting the entire list and I added a couple debug messages:

```
HAData HAClient::FetchData() {
  HTTPClient http;
  http.useHTTP10(true);
  std::string url = url_ + "/states/sensor.livingroom_temperature";
  http.begin(url.c_str());
  LOG("Fetching data from %s\n",url.c_str());
  std::string header = std::string("Bearer ") + token_;
  LOG("Header: %s\n", header.c_str());
  http.addHeader("Authorization", header.c_str());
  int code = http.GET();

  LOG("HTTP status code: %d\n", code);

  DynamicJsonDocument doc(EINK_HA_CLIENT_HTTP_RESP_SIZE);
  deserializeJson(doc, http.getStream());
  LOG("JSON: %d\n", doc.size());
 
  HAData data;
  LOG("Parsing Temp Data\n");

  for (const auto& el : doc.as<JsonArray>()) {
    std::string entity_id(el["entity_id"].as<std::string>());
    LOG("Entity ID: %s\n", entity_id); 

    ParseTempData(el.as<JsonObject>(), data.temp);
  }
```

This is the console output:

```
[14:40:01]After wifi 2248
[14:40:01]Fetching data from http://192.168.1.3:8123/api/states/sensor.livingroom_temperature
[14:40:01]Header: Bearer <mytoken>
[14:40:01]HTTP status code: 200
[14:40:01]JSON: 6
[14:40:01]Parsing Temp Data
[14:40:01]After getting data 2314
```
As you can see the for() with the parsing of data is never called...


Curl returns the correct data:
```
martin@EliteBook:~/platformio/eink-ha$ curl -H "Authorization: Bearer <mytoken>" http://192.168.1.3:8123/api/states/sensor.livingroom_temperature | jq .
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   413  100   413    0     0  41300      0 --:--:-- --:--:-- --:--:-- 45888
{
  "entity_id": "sensor.livingroom_temperature",
  "state": "23.6",
  "attributes": {
    "state_class": "measurement",
    "unit_of_measurement": "°C",
    "friendly_name": "Living Room Temperature",
    "device_class": "temperature"
  },
  "last_changed": "2021-11-14T13:16:02.789796+00:00",
  "last_updated": "2021-11-14T13:16:02.789796+00:00",
  "context": {
    "id": "a42e7be863eab745d51408a467bdd68d",
    "parent_id": null,
    "user_id": null
  }
}
```

If it's not too much too ask, can you just point me in the right direction for fetching the status of a single entity from its specific URL, esentially what I'm trying to do above? I'm somewhat confident that once I move past that point I can just hack things together to show the couple entities I want to display on the epaper.

Once again any help much appreciated.

**Comment by rbaron** [comment]
Hi @Plawasan,

I think I understand the issue. You changed the Home Assistant API endpoint being called from `/states`, which returns an array of entities, to `/states/:entity_id` (which returns an object representing a single entity).

So essentially you are now receiving a single object in the API call result. This explains why we see `"JSON: 6"` - there are 6 keys in this object. And the issue is you are trying to iterate on this object as if it were an array (`for (const auto& el : doc.as<JsonArray>()) ...`). You should be able to access its properties directly - we don't need the `for` loop anymore.

Let me know if that helps.

**Comment by Plawasan** [comment]
It sure did! I was expecting the result to be an array the size of 1 but apparently that's not the case.. I made a couple changes and things are starting to work:

```
  DynamicJsonDocument doc(EINK_HA_CLIENT_HTTP_RESP_SIZE);
  deserializeJson(doc, http.getStream());
  HAData ext_temp_data;
  std::string entity_id(doc["entity_id"].as<std::string>());
  ParseTempData(doc.as<JsonObject>(), ext_temp_data.temp);
```

I will not share anything else that I did to your code because it would probably make you weep but for what I need it works....

![image](https://user-images.githubusercontent.com/73796046/142196196-f3d83b29-3f57-4bf6-9d6f-c09a6da0f3ec.png)

**Comment by rbaron** [comment]
Glad to help!
